export const tn = {
    errorCodes: {
        "auth/ınvalıd-emaıl": "auth/ınvalıd-emaıl",
        "auth/emaıl-already-ın-use": "auth/emaıl-already-ın-use",
        "auth/wrong-password": "auth/wrong-password",
        "auth/user-not-found": "auth/user-not-found",
        "auth/network-request-faıled": "auth/network-request-faıled",
        "custom/fill-every-field": "custom/fill-every-field",
        "custom/invalid-url": "custom/invalid-url",
        "auth/too-many-requests": "auth/too-many-requests",
        "custom/invalid-email": "custom/invalid-email",
        "custom/password-mismatch": "custom/password-mismatch",
    },
    email: 'email',
    password: 'password',
    login: 'login',
    signUp: 'signUp',
    username: 'username',
    forgotPassword: 'forgotPassword',
    reset: 'reset',
    repeatPassword: 'repeatPassword',
    settings: 'settings',
    colorTheme: 'colorTheme',
    dark: 'dark',
    light: 'light',
    language: 'language',
    english: 'english',
    turkish: 'turkish',
    signOut: 'signOut',
    dontHaveAccount: 'dontHaveAccount',
    alreadyHaveAccount: 'alreadyHaveAccount',
    home: 'home',
    addApplication: 'addApplication',
    companyName: 'companyName',
    position: 'position',
    applicationDate: 'applicationDate',
    today: 'today',
    url: 'url',
    note: 'note',
    add: 'add',
    edit: 'edit',
    interviews: 'interviews',
    addInterview: 'addInterview',
    save: 'save',
    pickDate: 'pinckDate',
    interviewTitle: 'interviewTitle',
    interviewDetail: 'interviewDetail',
    flatListFooterText: 'flatListFooterText',
    flatListFooterTextConcluded: 'flatListFooterTextConcluded',
    emptyComponentAllText: 'emptyComponentAllText',
    emptyComponentConcludedText: 'emptyComponentConcludedText',
    delete: 'delete',
    error: 'error',
    concludedApplications: 'concludedApplications',
    okay: 'okay',
    conclusion: 'conclusion',
    all: 'all',
    concluded: 'concluded',
    filter: 'filter',
    fromOlderToNewer: 'fromOlderToNewer',
    fromNewerToOlder: 'fromNewerToOlder',
};

export const english = {
    [tn.email]: 'E-mail',
    [tn.password]: 'Password',
    [tn.login]: 'Login',
    [tn.signUp]: 'Sign Up',
    [tn.username]: 'Username',
    [tn.forgotPassword]: 'Forgot password?',
    [tn.reset]: 'Reset',
    [tn.repeatPassword]: 'Repeat password',
    [tn.settings]: 'Settings',
    [tn.colorTheme]: 'Color Theme',
    [tn.dark]: 'Dark',
    [tn.light]: 'Light',
    [tn.language]: 'Language',
    [tn.english]: 'English',
    [tn.turkish]: 'Türkçe',
    [tn.signOut]: 'Sign Out',
    [tn.dontHaveAccount]: "Don't have account?",
    [tn.alreadyHaveAccount]: 'Already have account?',
    [tn.home]: 'Home',
    [tn.addApplication]: 'Add job application',
    [tn.companyName]: 'Company Name',
    [tn.position]: 'Position',
    [tn.applicationDate]: 'Application Date',
    [tn.today]: 'Today',
    [tn.url]: 'URL',
    [tn.note]: 'Note',
    [tn.add]: 'Add',
    [tn.edit]: 'Edit',
    [tn.interviews]: 'Interviews',
    [tn.addInterview]: 'Add Interview',
    [tn.save]: 'Save',
    [tn.pickDate]: 'Pick date',
    [tn.interviewTitle]: 'Interview Title',
    [tn.interviewDetail]: 'Interview Details',
    [tn.flatListFooterText]: `You have applied to %{numberOfApplications} applications`,
    [tn.flatListFooterTextConcluded]: `%{numberOfApplications} of your applicaitons are concluded`,
    [tn.emptyComponentAllText]: `Welcome %{username}! You haven't added any aplication yet. To add an application press the plus icon on bottom right.`,
    [tn.emptyComponentConcludedText]: `Welcome %{username}! You don't have any concluded applications yet.`,
    [tn.delete]: 'Delete',
    [tn.error]: 'Error',
    [tn.errorCodes["auth/ınvalıd-emaıl"]]: 'Invalid E-mail! Please check e-mail.',
    [tn.errorCodes["auth/ınvalıd-emaıl"]]: 'Provided e-mail is already in use. If you forgot your password you can send a password reset request.',
    [tn.errorCodes["auth/wrong-password"]]: 'Wrong password. Try again.',
    [tn.errorCodes["auth/user-not-found"]]: 'A user with this credentials does not exist. You can sign up!',
    [tn.errorCodes["auth/network-request-faıled"]]: "Connection error. Check your network conntection.",
    [tn.errorCodes["custom/fill-every-field"]]: "Please fill every field!",
    [tn.errorCodes["custom/invalid-url"]]: "Invalid URL.",
    [tn.errorCodes["auth/too-many-requests"]]: "Too many requests. Try again in a few minutes.",
    [tn.errorCodes["custom/invalid-email"]]: "Invalid E-mail. Please enter a valid e-mail.",
    [tn.errorCodes["custom/password-mismatch"]]: "Passwords does not match. Please check passwords.",
    [tn.okay]: "Okay",
    [tn.conclusion]: "Conclusion",
    [tn.all]: "All",
    [tn.concluded]: "Concluded",
    [tn.filter]: 'Filter',
    [tn.fromOlderToNewer]: 'From Older to Newer',
    [tn.fromNewerToOlder]: 'From Newer to Older',
}

export const turkish = {
    [tn.email]: 'E-posta',
    [tn.password]: 'Şifre',
    [tn.login]: 'Giriş Yap',
    [tn.signUp]: 'Kayıt Ol',
    [tn.username]: 'Kullanıcı Adı',
    [tn.forgotPassword]: 'Şifreni mi unuttun?',
    [tn.reset]: 'Sıfırla',
    [tn.repeatPassword]: 'Şifre Tekrarı',
    [tn.settings]: 'Ayarlar',
    [tn.colorTheme]: 'Renk Teması',
    [tn.dark]: 'Karanlık',
    [tn.light]: 'Aydınlık',
    [tn.language]: 'Dil',
    [tn.english]: 'English',
    [tn.turkish]: 'Türkçe',
    [tn.signOut]: 'Çıkış Yap',
    [tn.dontHaveAccount]: 'Hesabın yok mu?',
    [tn.alreadyHaveAccount]: 'Zaten hesabın var mı?',
    [tn.home]: 'Anasayfa',
    [tn.addApplication]: 'Yeni başvuru ekle',
    [tn.companyName]: 'Şirket Adı',
    [tn.position]: 'Pozisyon',
    [tn.applicationDate]: 'Başvuru Tarihi',
    [tn.today]: 'Bugün',
    [tn.url]: 'URL',
    [tn.note]: 'Not',
    [tn.add]: 'Ekle',
    [tn.edit]: 'Düzenle',
    [tn.interviews]: 'Görüşmeler',
    [tn.addInterview]: 'Görüşme ekle',
    [tn.save]: 'Kaydet',
    [tn.pickDate]: 'Tarih seç',
    [tn.interviewTitle]: 'Görüşme Başlığı',
    [tn.interviewDetail]: 'Görüşme Detayı',
    [tn.flatListFooterText]: `%{numberOfApplications} ilana başvurdun`,
    [tn.flatListFooterTextConcluded]: `Başvurularının %{numberOfApplications} tanesi sonuçlanmış`,
    [tn.emptyComponentAllText]: `Hoşgeldin %{username}! Henüz bir başvuru eklemedin. Başvuru eklemek için sağ alttaki artıya tıkla.`,
    [tn.emptyComponentConcludedText]: `Hoşgeldin %{username}! Henüz sonuçlanmış başvurun yok.`,
    [tn.delete]: 'Sil',
    [tn.error]: 'Hata',
    [tn.errorCodes["auth/ınvalıd-emaıl"]]: 'Geçersiz E-posta. Lütfen e-posta adresinizi kontrol edin.',
    [tn.errorCodes["auth/emaıl-already-ın-use"]]: 'Girilen e-postaya ait bir hesap zaten var. Şifreni unuttuysan şifre sıfırlama isteği gönderebilirsin.',
    [tn.errorCodes["auth/wrong-password"]]: 'Yanlış şifre. Tekrar dene.',
    [tn.errorCodes["auth/user-not-found"]]: 'Bu bilgilere ait bir kullanıcı bulunamadı. Kayıt olabilirsin.',
    [tn.errorCodes["auth/network-request-faıled"]]: 'Bağlantı hatası. Ağ bağlantınızı kontrol edin.',
    [tn.errorCodes["custom/fill-every-field"]]: "Lütfen tüm alanları doldurun!",
    [tn.errorCodes["custom/invalid-url"]]: "Geçersiz URL.",
    [tn.errorCodes["auth/too-many-requests"]]: "Çok fazla istek gönderildi. Birkaç dakika sonra tekrar deneyin.",
    [tn.errorCodes["custom/invalid-email"]]: "Geçersiz E-posta. Lütfen geçerli bir e-posta adresi giriniz.",
    [tn.errorCodes["custom/password-mismatch"]]: "Şifreler eşlemiyor. Şifreleri kontrol edin.",
    [tn.okay]: 'Tamam',
    [tn.conclusion]: 'Sonuç',
    [tn.all]: 'Hepsi',
    [tn.concluded]: 'Sonuçlanmış',
    [tn.filter]: 'Filtrele',
    [tn.fromOlderToNewer]: 'Eskiden Yeniye',
    [tn.fromNewerToOlder]: 'Yeniden Eskiye',
}