export const tn = {
    email: 'email',
    password: 'password',
    login: 'login',
    signUp: 'signUp',
    username: 'username',
    forgotPassword: 'forgotPassword',
    reset: 'reset',
    repeatPassword: 'repeatPassword',
    settings: 'settings',
    colorTheme: 'colorTheme',
    dark: 'dark',
    light: 'light',
    language: 'language',
    english: 'english',
    turkish: 'turkish',
    signOut: 'signOut',
    dontHaveAccount: 'dontHaveAccount',
    alreadyHaveAccount: 'alreadyHaveAccount',
    home: 'home',
    addApplication: 'addApplication',
    companyName: 'companyName',
    position: 'position',
    applicationDate: 'applicationDate',
    today: 'today',
    url: 'url',
    note: 'note',
    add: 'add',
    edit: 'edit',
    interviews: 'interviews',
    addInterview: 'addInterview',
    save: 'save',
    pickDate: 'pinckDate',
    interviewTitle: 'interviewTitle',
    interviewDetail: 'interviewDetail',
    flatListFooterText: 'flatListFooterText',
    emptyComponentText: 'emptyComponentText',
    delete: 'delete',
};

export const english = {
    [tn.email]: 'E-mail',
    [tn.password]: 'Password',
    [tn.login]: 'Login',
    [tn.signUp]: 'Sign Up',
    [tn.username]: 'Username',
    [tn.forgotPassword]: 'Forgot password?',
    [tn.reset]: 'Reset',
    [tn.repeatPassword]: 'Repeat password',
    [tn.settings]: 'Settings',
    [tn.colorTheme]: 'Color Theme',
    [tn.dark]: 'Dark',
    [tn.light]: 'Light',
    [tn.language]: 'Language',
    [tn.english]: 'English',
    [tn.turkish]: 'Türkçe',
    [tn.signOut]: 'Sign Out',
    [tn.dontHaveAccount]: "Don't have account?",
    [tn.alreadyHaveAccount]: 'Already have account?',
    [tn.home]: 'Home',
    [tn.addApplication]: 'Add job application',
    [tn.companyName]: 'Company Name',
    [tn.position]: 'Position',
    [tn.applicationDate]: 'Application Date',
    [tn.today]: 'Today',
    [tn.url]: 'URL',
    [tn.note]: 'Note',
    [tn.add]: 'Add',
    [tn.edit]: 'Edit',
    [tn.interviews]: 'Interviews',
    [tn.addInterview]: 'Add Interview',
    [tn.save]: 'Save',
    [tn.pickDate]: 'Pick date',
    [tn.interviewTitle]: 'Interview Title',
    [tn.interviewDetail]: 'Interview Details',
    [tn.flatListFooterText]: `You have applied to %{numberOfApplications} applications`,
    [tn.emptyComponentText]: `Welcome %{username}! You haven't added any aplication yet. To add an application press the plus icon on bottom right.`,
    [tn.delete]: 'Delete',
}

export const turkish = {
    [tn.email]: 'E-posta',
    [tn.password]: 'Şifre',
    [tn.login]: 'Giriş Yap',
    [tn.signUp]: 'Kayıt Ol',
    [tn.username]: 'Kullanıcı Adı',
    [tn.forgotPassword]: 'Şifreni mi unuttun?',
    [tn.reset]: 'Sıfırla',
    [tn.repeatPassword]: 'Şifre Tekrarı',
    [tn.settings]: 'Ayarlar',
    [tn.colorTheme]: 'Renk Teması',
    [tn.dark]: 'Karanlık',
    [tn.light]: 'Aydınlık',
    [tn.language]: 'Dil',
    [tn.english]: 'English',
    [tn.turkish]: 'Türkçe',
    [tn.signOut]: 'Çıkış Yap',
    [tn.dontHaveAccount]: 'Hesabın yok mu?',
    [tn.alreadyHaveAccount]: 'Zaten hesabın var mı?',
    [tn.home]: 'Anasayfa',
    [tn.addApplication]: 'Yeni başvuru ekle',
    [tn.companyName]: 'Şirket Adı',
    [tn.position]: 'Pozisyon',
    [tn.applicationDate]: 'Başvuru Tarihi',
    [tn.today]: 'Bugün',
    [tn.url]: 'URL',
    [tn.note]: 'Not',
    [tn.add]: 'Ekle',
    [tn.edit]: 'Düzenle',
    [tn.interviews]: 'Görüşmeler',
    [tn.addInterview]: 'Görüşme ekle',
    [tn.save]: 'Kaydet',
    [tn.pickDate]: 'Tarih seç',
    [tn.interviewTitle]: 'Görüşme Başlığı',
    [tn.interviewDetail]: 'Görüşme Detayı',
    [tn.flatListFooterText]: `%{numberOfApplications} ilana başvurdun`,
    [tn.emptyComponentText]: `Hoşgeldin %{username}! Henüz bir başvuru eklemedin. Başvuru eklemek için sağ alttaki artıya tıkla.`,
    [tn.delete]: 'Sil',
}